require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DonosController do

  # This should return the minimal set of attributes required to create a valid
  # Dono. As you add validations to Dono, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "codigo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DonosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all donos as @donos" do
      dono = Dono.create! valid_attributes
      get :index, {}, valid_session
      assigns(:donos).should eq([dono])
    end
  end

  describe "GET show" do
    it "assigns the requested dono as @dono" do
      dono = Dono.create! valid_attributes
      get :show, {:id => dono.to_param}, valid_session
      assigns(:dono).should eq(dono)
    end
  end

  describe "GET new" do
    it "assigns a new dono as @dono" do
      get :new, {}, valid_session
      assigns(:dono).should be_a_new(Dono)
    end
  end

  describe "GET edit" do
    it "assigns the requested dono as @dono" do
      dono = Dono.create! valid_attributes
      get :edit, {:id => dono.to_param}, valid_session
      assigns(:dono).should eq(dono)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dono" do
        expect {
          post :create, {:dono => valid_attributes}, valid_session
        }.to change(Dono, :count).by(1)
      end

      it "assigns a newly created dono as @dono" do
        post :create, {:dono => valid_attributes}, valid_session
        assigns(:dono).should be_a(Dono)
        assigns(:dono).should be_persisted
      end

      it "redirects to the created dono" do
        post :create, {:dono => valid_attributes}, valid_session
        response.should redirect_to(Dono.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dono as @dono" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dono.any_instance.stub(:save).and_return(false)
        post :create, {:dono => { "codigo" => "invalid value" }}, valid_session
        assigns(:dono).should be_a_new(Dono)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dono.any_instance.stub(:save).and_return(false)
        post :create, {:dono => { "codigo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dono" do
        dono = Dono.create! valid_attributes
        # Assuming there are no other donos in the database, this
        # specifies that the Dono created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dono.any_instance.should_receive(:update).with({ "codigo" => "MyString" })
        put :update, {:id => dono.to_param, :dono => { "codigo" => "MyString" }}, valid_session
      end

      it "assigns the requested dono as @dono" do
        dono = Dono.create! valid_attributes
        put :update, {:id => dono.to_param, :dono => valid_attributes}, valid_session
        assigns(:dono).should eq(dono)
      end

      it "redirects to the dono" do
        dono = Dono.create! valid_attributes
        put :update, {:id => dono.to_param, :dono => valid_attributes}, valid_session
        response.should redirect_to(dono)
      end
    end

    describe "with invalid params" do
      it "assigns the dono as @dono" do
        dono = Dono.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dono.any_instance.stub(:save).and_return(false)
        put :update, {:id => dono.to_param, :dono => { "codigo" => "invalid value" }}, valid_session
        assigns(:dono).should eq(dono)
      end

      it "re-renders the 'edit' template" do
        dono = Dono.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dono.any_instance.stub(:save).and_return(false)
        put :update, {:id => dono.to_param, :dono => { "codigo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dono" do
      dono = Dono.create! valid_attributes
      expect {
        delete :destroy, {:id => dono.to_param}, valid_session
      }.to change(Dono, :count).by(-1)
    end

    it "redirects to the donos list" do
      dono = Dono.create! valid_attributes
      delete :destroy, {:id => dono.to_param}, valid_session
      response.should redirect_to(donos_url)
    end
  end

end
