require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QtdeambientesController do

  # This should return the minimal set of attributes required to create a valid
  # Qtdeambiente. As you add validations to Qtdeambiente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "qtde" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QtdeambientesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all qtdeambientes as @qtdeambientes" do
      qtdeambiente = Qtdeambiente.create! valid_attributes
      get :index, {}, valid_session
      assigns(:qtdeambientes).should eq([qtdeambiente])
    end
  end

  describe "GET show" do
    it "assigns the requested qtdeambiente as @qtdeambiente" do
      qtdeambiente = Qtdeambiente.create! valid_attributes
      get :show, {:id => qtdeambiente.to_param}, valid_session
      assigns(:qtdeambiente).should eq(qtdeambiente)
    end
  end

  describe "GET new" do
    it "assigns a new qtdeambiente as @qtdeambiente" do
      get :new, {}, valid_session
      assigns(:qtdeambiente).should be_a_new(Qtdeambiente)
    end
  end

  describe "GET edit" do
    it "assigns the requested qtdeambiente as @qtdeambiente" do
      qtdeambiente = Qtdeambiente.create! valid_attributes
      get :edit, {:id => qtdeambiente.to_param}, valid_session
      assigns(:qtdeambiente).should eq(qtdeambiente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Qtdeambiente" do
        expect {
          post :create, {:qtdeambiente => valid_attributes}, valid_session
        }.to change(Qtdeambiente, :count).by(1)
      end

      it "assigns a newly created qtdeambiente as @qtdeambiente" do
        post :create, {:qtdeambiente => valid_attributes}, valid_session
        assigns(:qtdeambiente).should be_a(Qtdeambiente)
        assigns(:qtdeambiente).should be_persisted
      end

      it "redirects to the created qtdeambiente" do
        post :create, {:qtdeambiente => valid_attributes}, valid_session
        response.should redirect_to(Qtdeambiente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qtdeambiente as @qtdeambiente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qtdeambiente.any_instance.stub(:save).and_return(false)
        post :create, {:qtdeambiente => { "qtde" => "invalid value" }}, valid_session
        assigns(:qtdeambiente).should be_a_new(Qtdeambiente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qtdeambiente.any_instance.stub(:save).and_return(false)
        post :create, {:qtdeambiente => { "qtde" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qtdeambiente" do
        qtdeambiente = Qtdeambiente.create! valid_attributes
        # Assuming there are no other qtdeambientes in the database, this
        # specifies that the Qtdeambiente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Qtdeambiente.any_instance.should_receive(:update).with({ "qtde" => "1" })
        put :update, {:id => qtdeambiente.to_param, :qtdeambiente => { "qtde" => "1" }}, valid_session
      end

      it "assigns the requested qtdeambiente as @qtdeambiente" do
        qtdeambiente = Qtdeambiente.create! valid_attributes
        put :update, {:id => qtdeambiente.to_param, :qtdeambiente => valid_attributes}, valid_session
        assigns(:qtdeambiente).should eq(qtdeambiente)
      end

      it "redirects to the qtdeambiente" do
        qtdeambiente = Qtdeambiente.create! valid_attributes
        put :update, {:id => qtdeambiente.to_param, :qtdeambiente => valid_attributes}, valid_session
        response.should redirect_to(qtdeambiente)
      end
    end

    describe "with invalid params" do
      it "assigns the qtdeambiente as @qtdeambiente" do
        qtdeambiente = Qtdeambiente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qtdeambiente.any_instance.stub(:save).and_return(false)
        put :update, {:id => qtdeambiente.to_param, :qtdeambiente => { "qtde" => "invalid value" }}, valid_session
        assigns(:qtdeambiente).should eq(qtdeambiente)
      end

      it "re-renders the 'edit' template" do
        qtdeambiente = Qtdeambiente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qtdeambiente.any_instance.stub(:save).and_return(false)
        put :update, {:id => qtdeambiente.to_param, :qtdeambiente => { "qtde" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qtdeambiente" do
      qtdeambiente = Qtdeambiente.create! valid_attributes
      expect {
        delete :destroy, {:id => qtdeambiente.to_param}, valid_session
      }.to change(Qtdeambiente, :count).by(-1)
    end

    it "redirects to the qtdeambientes list" do
      qtdeambiente = Qtdeambiente.create! valid_attributes
      delete :destroy, {:id => qtdeambiente.to_param}, valid_session
      response.should redirect_to(qtdeambientes_url)
    end
  end

end
