require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuantidadeambientesController do

  # This should return the minimal set of attributes required to create a valid
  # Quantidadeambiente. As you add validations to Quantidadeambiente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "quantidade" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuantidadeambientesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all quantidadeambientes as @quantidadeambientes" do
      quantidadeambiente = Quantidadeambiente.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quantidadeambientes).should eq([quantidadeambiente])
    end
  end

  describe "GET show" do
    it "assigns the requested quantidadeambiente as @quantidadeambiente" do
      quantidadeambiente = Quantidadeambiente.create! valid_attributes
      get :show, {:id => quantidadeambiente.to_param}, valid_session
      assigns(:quantidadeambiente).should eq(quantidadeambiente)
    end
  end

  describe "GET new" do
    it "assigns a new quantidadeambiente as @quantidadeambiente" do
      get :new, {}, valid_session
      assigns(:quantidadeambiente).should be_a_new(Quantidadeambiente)
    end
  end

  describe "GET edit" do
    it "assigns the requested quantidadeambiente as @quantidadeambiente" do
      quantidadeambiente = Quantidadeambiente.create! valid_attributes
      get :edit, {:id => quantidadeambiente.to_param}, valid_session
      assigns(:quantidadeambiente).should eq(quantidadeambiente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Quantidadeambiente" do
        expect {
          post :create, {:quantidadeambiente => valid_attributes}, valid_session
        }.to change(Quantidadeambiente, :count).by(1)
      end

      it "assigns a newly created quantidadeambiente as @quantidadeambiente" do
        post :create, {:quantidadeambiente => valid_attributes}, valid_session
        assigns(:quantidadeambiente).should be_a(Quantidadeambiente)
        assigns(:quantidadeambiente).should be_persisted
      end

      it "redirects to the created quantidadeambiente" do
        post :create, {:quantidadeambiente => valid_attributes}, valid_session
        response.should redirect_to(Quantidadeambiente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quantidadeambiente as @quantidadeambiente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Quantidadeambiente.any_instance.stub(:save).and_return(false)
        post :create, {:quantidadeambiente => { "quantidade" => "invalid value" }}, valid_session
        assigns(:quantidadeambiente).should be_a_new(Quantidadeambiente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Quantidadeambiente.any_instance.stub(:save).and_return(false)
        post :create, {:quantidadeambiente => { "quantidade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quantidadeambiente" do
        quantidadeambiente = Quantidadeambiente.create! valid_attributes
        # Assuming there are no other quantidadeambientes in the database, this
        # specifies that the Quantidadeambiente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Quantidadeambiente.any_instance.should_receive(:update).with({ "quantidade" => "MyString" })
        put :update, {:id => quantidadeambiente.to_param, :quantidadeambiente => { "quantidade" => "MyString" }}, valid_session
      end

      it "assigns the requested quantidadeambiente as @quantidadeambiente" do
        quantidadeambiente = Quantidadeambiente.create! valid_attributes
        put :update, {:id => quantidadeambiente.to_param, :quantidadeambiente => valid_attributes}, valid_session
        assigns(:quantidadeambiente).should eq(quantidadeambiente)
      end

      it "redirects to the quantidadeambiente" do
        quantidadeambiente = Quantidadeambiente.create! valid_attributes
        put :update, {:id => quantidadeambiente.to_param, :quantidadeambiente => valid_attributes}, valid_session
        response.should redirect_to(quantidadeambiente)
      end
    end

    describe "with invalid params" do
      it "assigns the quantidadeambiente as @quantidadeambiente" do
        quantidadeambiente = Quantidadeambiente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Quantidadeambiente.any_instance.stub(:save).and_return(false)
        put :update, {:id => quantidadeambiente.to_param, :quantidadeambiente => { "quantidade" => "invalid value" }}, valid_session
        assigns(:quantidadeambiente).should eq(quantidadeambiente)
      end

      it "re-renders the 'edit' template" do
        quantidadeambiente = Quantidadeambiente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Quantidadeambiente.any_instance.stub(:save).and_return(false)
        put :update, {:id => quantidadeambiente.to_param, :quantidadeambiente => { "quantidade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quantidadeambiente" do
      quantidadeambiente = Quantidadeambiente.create! valid_attributes
      expect {
        delete :destroy, {:id => quantidadeambiente.to_param}, valid_session
      }.to change(Quantidadeambiente, :count).by(-1)
    end

    it "redirects to the quantidadeambientes list" do
      quantidadeambiente = Quantidadeambiente.create! valid_attributes
      delete :destroy, {:id => quantidadeambiente.to_param}, valid_session
      response.should redirect_to(quantidadeambientes_url)
    end
  end

end
